name: Build-Chaitin-Plus

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run Python scripts
      run: |
        python /home/runner/work/Comprehensive-Network-Defense/Comprehensive-Network-Defense/Scripts/IP-to-CIDR.py "/home/runner/work/Comprehensive-Network-Defense/Comprehensive-Network-Defense/IPs/Chaitin.txt" "/home/runner/work/Comprehensive-Network-Defense/Comprehensive-Network-Defense/IPs/Chaitin-Plus.txt"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Chaitin-Plus.txt
        path: /home/runner/work/Comprehensive-Network-Defense/Comprehensive-Network-Defense/IPs/Chaitin-Plus.txt

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add IPs/*
        git commit -m "Update files"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
